name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  # arm32_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3  
    
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
        
  #   - name: CMake build and run
  #     run: |
  #       docker run --platform linux/arm/v7 --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp arm32v7/gcc bash -c "apt update && apt install -y cmake; mkdir build && cmake -B build && cmake --build build --config ${{env.BUILD_TYPE}} && cmake --install build; ./dist/main ./images/AllSupportedBarcodeTypes.png ./license-key.txt"
        
  #   - name: Archive Release
  #     uses: thedoctor0/zip-release@main
  #     with:
  #       type: 'zip'
  #       filename: arm32.zip
  #       exclusions: '*.git* /*node_modules/* .editorconfig'
  #       path: ${{github.workspace}}/dist

  #   - uses: actions/upload-artifact@v2
  #     with:
  #       path: ./*.zip

  # arm64_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3  
    
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
        
  #   - name: CMake build and run
  #     run: |
  #       docker run --platform linux/arm64/v8 --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp arm64v8/gcc bash -c "apt update && apt install -y cmake; mkdir build && cmake -B build && cmake --build build --config ${{env.BUILD_TYPE}} && cmake --install build; ./dist/main ./images/AllSupportedBarcodeTypes.png ./license-key.txt"
        
  #   - name: Archive Release
  #     uses: thedoctor0/zip-release@main
  #     with:
  #       type: 'zip'
  #       filename: arm64.zip
  #       exclusions: '*.git* /*node_modules/* .editorconfig'
  #       path: ${{github.workspace}}/dist

  #   - uses: actions/upload-artifact@v2
  #     with:
  #       path: ./*.zip

  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: x86_64 build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64
          
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -S ${{ github.workspace }}/examples/command-line -B ${{github.workspace}}/examples/command-line/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build command line program
      # Build your program with the given configuration
      run: |
        cmake --build ${{github.workspace}}/examples/command-line/build --config ${{env.BUILD_TYPE}}
        # cmake --install ${{github.workspace}}/examples/command-line/build

    # - name: Test
    #   working-directory: ${{github.workspace}}/examples/command-line/dist
    #   run: ./main  ../../../../images/AllSupportedBarcodeTypes.png ../../../../license-key.txt
        
    # - name: Archive Release
    #   uses: thedoctor0/zip-release@main
    #   with:
    #     type: 'zip'
    #     filename: ${{ matrix.os }}.zip
    #     exclusions: '*.git* /*node_modules/* .editorconfig'
    #     path: ${{github.workspace}}/dist

    # - uses: actions/upload-artifact@v2
    #   with:
    #     path: ./*.zip
